services:

  backend:
    container_name: template-backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - example.env
    volumes:
      - ./src:/run/src
      - ./alembic:/run/alembic
      - ./alembic.ini:/run/alembic.ini
      - ./run_alembic.sh:/run/run_alembic.sh
    environment:
      - PYTHONPATH=/run
      - DEV=true
    command: "python3.11 -m fastapi run src/server.py --host 0.0.0.0 --port 8000 --reload"
    networks:
      - shared_network

  redis:
    container_name: template-redis
    image: redis:7.0-alpine
    restart: always
    networks:
      - shared_network
    volumes:
      - ./volume/redis_data:/data

  mysql:
    container_name: template-mysql
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
      MYSQL_DATABASE: template_db
    volumes:
      - ./volume/mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - shared_network

  mysql-backup:
    container_name: template-mysql-backup
    build:
      context: ./mysql-backup
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: template_db
      BACKUP_SCHEDULE: "0 2 * * *"  # Daily at 2 AM
      BACKUP_RETENTION_DAYS: 7       # Keep backups for 7 days
      BACKUP_ON_STARTUP: "true"      # Create backup when container starts
    volumes:
      - ./volume/mysql_backups:/backups
    networks:
      - shared_network

  adminer:
    container_name: template-adminer
    image: adminer
    restart: always
    ports:
      - "8001:8080"
    networks:
      - shared_network

  minio:
    image: quay.io/minio/minio
    container_name: template-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./volume/minio_data:/data
      - ./init-minio.sh:/init-minio.sh:ro
      - ./minio-entrypoint.sh:/minio-entrypoint.sh:ro
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin1234
    networks: 
      - shared_network
    entrypoint: /bin/sh
    command: ["/minio-entrypoint.sh"]

networks:
  shared_network:
    driver: bridge